/*
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractCsvDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.xtext.first.csvdsl.csvDsl.CsvDslPackage.eINSTANCE);
		return result;
	}
}
