/**
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.csvDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Assign</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.Assign#getVal <em>Val</em>}</li>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.Assign#getOp <em>Op</em>}</li>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.Assign#getVar <em>Var</em>}</li>
 * </ul>
 *
 * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getAssign()
 * @model
 * @generated
 */
public interface Assign extends Statement
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference.
   * @see #setVal(Csv_variable)
   * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getAssign_Val()
   * @model containment="true"
   * @generated
   */
  Csv_variable getVal();

  /**
   * Sets the value of the '{@link org.xtext.first.csvdsl.csvDsl.Assign#getVal <em>Val</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' containment reference.
   * @see #getVal()
   * @generated
   */
  void setVal(Csv_variable value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' containment reference.
   * @see #setOp(EObject)
   * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getAssign_Op()
   * @model containment="true"
   * @generated
   */
  EObject getOp();

  /**
   * Sets the value of the '{@link org.xtext.first.csvdsl.csvDsl.Assign#getOp <em>Op</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' containment reference.
   * @see #getOp()
   * @generated
   */
  void setOp(EObject value);

  /**
   * Returns the value of the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var</em>' containment reference.
   * @see #setVar(Int_variable)
   * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getAssign_Var()
   * @model containment="true"
   * @generated
   */
  Int_variable getVar();

  /**
   * Sets the value of the '{@link org.xtext.first.csvdsl.csvDsl.Assign#getVar <em>Var</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Var</em>' containment reference.
   * @see #getVar()
   * @generated
   */
  void setVar(Int_variable value);

} // Assign
