/**
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.csvDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Col Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.ColRange#getColumn <em>Column</em>}</li>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.ColRange#getColumnStart <em>Column Start</em>}</li>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.ColRange#getColumnEnd <em>Column End</em>}</li>
 * </ul>
 *
 * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getColRange()
 * @model
 * @generated
 */
public interface ColRange extends Range
{
  /**
   * Returns the value of the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' attribute.
   * @see #setColumn(int)
   * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getColRange_Column()
   * @model
   * @generated
   */
  int getColumn();

  /**
   * Sets the value of the '{@link org.xtext.first.csvdsl.csvDsl.ColRange#getColumn <em>Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column</em>' attribute.
   * @see #getColumn()
   * @generated
   */
  void setColumn(int value);

  /**
   * Returns the value of the '<em><b>Column Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column Start</em>' attribute.
   * @see #setColumnStart(int)
   * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getColRange_ColumnStart()
   * @model
   * @generated
   */
  int getColumnStart();

  /**
   * Sets the value of the '{@link org.xtext.first.csvdsl.csvDsl.ColRange#getColumnStart <em>Column Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column Start</em>' attribute.
   * @see #getColumnStart()
   * @generated
   */
  void setColumnStart(int value);

  /**
   * Returns the value of the '<em><b>Column End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column End</em>' attribute.
   * @see #setColumnEnd(int)
   * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getColRange_ColumnEnd()
   * @model
   * @generated
   */
  int getColumnEnd();

  /**
   * Sets the value of the '{@link org.xtext.first.csvdsl.csvDsl.ColRange#getColumnEnd <em>Column End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column End</em>' attribute.
   * @see #getColumnEnd()
   * @generated
   */
  void setColumnEnd(int value);

} // ColRange
