/**
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.csvDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.first.csvdsl.csvDsl.CsvDslFactory
 * @model kind="package"
 * @generated
 */
public interface CsvDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "csvDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/first/csvdsl/CsvDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "csvDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CsvDslPackage eINSTANCE = org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.ModelImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Statement</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__STATEMENT = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.StatementImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.CsvOperationImpl <em>Csv Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvOperationImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getCsvOperation()
   * @generated
   */
  int CSV_OPERATION = 2;

  /**
   * The number of structural features of the '<em>Csv Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.IntOperationImpl <em>Int Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.IntOperationImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getIntOperation()
   * @generated
   */
  int INT_OPERATION = 3;

  /**
   * The number of structural features of the '<em>Int Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_OPERATION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.AssignImpl <em>Assign</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.AssignImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getAssign()
   * @generated
   */
  int ASSIGN = 4;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN__VAL = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Op</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN__OP = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN__VAR = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Assign</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.SaveImpl <em>Save</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.SaveImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getSave()
   * @generated
   */
  int SAVE = 5;

  /**
   * The feature id for the '<em><b>Declared csv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE__DECLARED_CSV = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Filename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE__FILENAME = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Save</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SAVE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.PrintImpl <em>Print</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.PrintImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getPrint()
   * @generated
   */
  int PRINT = 6;

  /**
   * The feature id for the '<em><b>Val</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT__VAL = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Print</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRINT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.LoadImpl <em>Load</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.LoadImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getLoad()
   * @generated
   */
  int LOAD = 7;

  /**
   * The feature id for the '<em><b>Filename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD__FILENAME = CSV_OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Load</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_FEATURE_COUNT = CSV_OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.SumImpl <em>Sum</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.SumImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getSum()
   * @generated
   */
  int SUM = 8;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM__VAR = INT_OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Selection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM__SELECTION = INT_OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Sum</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUM_FEATURE_COUNT = INT_OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.ProductImpl <em>Product</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.ProductImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getProduct()
   * @generated
   */
  int PRODUCT = 9;

  /**
   * The feature id for the '<em><b>Var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT__VAR = INT_OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Selection</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT__SELECTION = INT_OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Product</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PRODUCT_FEATURE_COUNT = INT_OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.DirectImpl <em>Direct</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.DirectImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getDirect()
   * @generated
   */
  int DIRECT = 10;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECT__VAL = INT_OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Direct</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIRECT_FEATURE_COUNT = INT_OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.SelectImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 11;

  /**
   * The feature id for the '<em><b>New Csv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__NEW_CSV = CSV_OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Csv var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__CSV_VAR = CSV_OPERATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__RANGE = CSV_OPERATION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = CSV_OPERATION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.DropImpl <em>Drop</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.DropImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getDrop()
   * @generated
   */
  int DROP = 12;

  /**
   * The feature id for the '<em><b>New Csv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP__NEW_CSV = CSV_OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Csv var</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP__CSV_VAR = CSV_OPERATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP__RANGE = CSV_OPERATION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Drop</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DROP_FEATURE_COUNT = CSV_OPERATION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.RangeImpl <em>Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.RangeImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getRange()
   * @generated
   */
  int RANGE = 13;

  /**
   * The number of structural features of the '<em>Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.RowRangeImpl <em>Row Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.RowRangeImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getRowRange()
   * @generated
   */
  int ROW_RANGE = 14;

  /**
   * The feature id for the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RANGE__ROW = RANGE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Row Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RANGE__ROW_START = RANGE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Row End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RANGE__ROW_END = RANGE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Row Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RANGE_FEATURE_COUNT = RANGE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.ColRangeImpl <em>Col Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.ColRangeImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getColRange()
   * @generated
   */
  int COL_RANGE = 15;

  /**
   * The feature id for the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_RANGE__COLUMN = RANGE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Column Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_RANGE__COLUMN_START = RANGE_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Column End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_RANGE__COLUMN_END = RANGE_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Col Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COL_RANGE_FEATURE_COUNT = RANGE_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.Csv_variableImpl <em>Csv variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.Csv_variableImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getCsv_variable()
   * @generated
   */
  int CSV_VARIABLE = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Csv variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CSV_VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.first.csvdsl.csvDsl.impl.Int_variableImpl <em>Int variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.first.csvdsl.csvDsl.impl.Int_variableImpl
   * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getInt_variable()
   * @generated
   */
  int INT_VARIABLE = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Int variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VARIABLE_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.first.csvdsl.csvDsl.Model#getStatement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statement</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Model#getStatement()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Statement();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.CsvOperation <em>Csv Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Csv Operation</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.CsvOperation
   * @generated
   */
  EClass getCsvOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.IntOperation <em>Int Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Operation</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.IntOperation
   * @generated
   */
  EClass getIntOperation();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Assign <em>Assign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assign</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Assign
   * @generated
   */
  EClass getAssign();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Assign#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Assign#getVal()
   * @see #getAssign()
   * @generated
   */
  EReference getAssign_Val();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Assign#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Op</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Assign#getOp()
   * @see #getAssign()
   * @generated
   */
  EReference getAssign_Op();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Assign#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Assign#getVar()
   * @see #getAssign()
   * @generated
   */
  EReference getAssign_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Save <em>Save</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Save</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Save
   * @generated
   */
  EClass getSave();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Save#getDeclared_csv <em>Declared csv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Declared csv</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Save#getDeclared_csv()
   * @see #getSave()
   * @generated
   */
  EReference getSave_Declared_csv();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.first.csvdsl.csvDsl.Save#getFilename <em>Filename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Filename</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Save#getFilename()
   * @see #getSave()
   * @generated
   */
  EAttribute getSave_Filename();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Print <em>Print</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Print</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Print
   * @generated
   */
  EClass getPrint();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Print#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Val</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Print#getVal()
   * @see #getPrint()
   * @generated
   */
  EReference getPrint_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Load <em>Load</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Load</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Load
   * @generated
   */
  EClass getLoad();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.first.csvdsl.csvDsl.Load#getFilename <em>Filename</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Filename</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Load#getFilename()
   * @see #getLoad()
   * @generated
   */
  EAttribute getLoad_Filename();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Sum <em>Sum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sum</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Sum
   * @generated
   */
  EClass getSum();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Sum#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Sum#getVar()
   * @see #getSum()
   * @generated
   */
  EReference getSum_Var();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Sum#getSelection <em>Selection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selection</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Sum#getSelection()
   * @see #getSum()
   * @generated
   */
  EReference getSum_Selection();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Product <em>Product</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Product</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Product
   * @generated
   */
  EClass getProduct();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Product#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Var</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Product#getVar()
   * @see #getProduct()
   * @generated
   */
  EReference getProduct_Var();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Product#getSelection <em>Selection</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selection</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Product#getSelection()
   * @see #getProduct()
   * @generated
   */
  EReference getProduct_Selection();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Direct <em>Direct</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Direct</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Direct
   * @generated
   */
  EClass getDirect();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.first.csvdsl.csvDsl.Direct#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Direct#getVal()
   * @see #getDirect()
   * @generated
   */
  EAttribute getDirect_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Select#getNewCsv <em>New Csv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>New Csv</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Select#getNewCsv()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_NewCsv();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Select#getCsv_var <em>Csv var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Csv var</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Select#getCsv_var()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_Csv_var();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Select#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Range</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Select#getRange()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_Range();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Drop <em>Drop</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Drop</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Drop
   * @generated
   */
  EClass getDrop();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Drop#getNewCsv <em>New Csv</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>New Csv</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Drop#getNewCsv()
   * @see #getDrop()
   * @generated
   */
  EReference getDrop_NewCsv();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Drop#getCsv_var <em>Csv var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Csv var</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Drop#getCsv_var()
   * @see #getDrop()
   * @generated
   */
  EReference getDrop_Csv_var();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.first.csvdsl.csvDsl.Drop#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Range</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Drop#getRange()
   * @see #getDrop()
   * @generated
   */
  EReference getDrop_Range();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Range <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Range
   * @generated
   */
  EClass getRange();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.RowRange <em>Row Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Range</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.RowRange
   * @generated
   */
  EClass getRowRange();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.first.csvdsl.csvDsl.RowRange#getRow <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Row</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.RowRange#getRow()
   * @see #getRowRange()
   * @generated
   */
  EAttribute getRowRange_Row();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.first.csvdsl.csvDsl.RowRange#getRowStart <em>Row Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Row Start</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.RowRange#getRowStart()
   * @see #getRowRange()
   * @generated
   */
  EAttribute getRowRange_RowStart();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.first.csvdsl.csvDsl.RowRange#getRowEnd <em>Row End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Row End</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.RowRange#getRowEnd()
   * @see #getRowRange()
   * @generated
   */
  EAttribute getRowRange_RowEnd();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.ColRange <em>Col Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Col Range</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.ColRange
   * @generated
   */
  EClass getColRange();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.first.csvdsl.csvDsl.ColRange#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Column</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.ColRange#getColumn()
   * @see #getColRange()
   * @generated
   */
  EAttribute getColRange_Column();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.first.csvdsl.csvDsl.ColRange#getColumnStart <em>Column Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Column Start</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.ColRange#getColumnStart()
   * @see #getColRange()
   * @generated
   */
  EAttribute getColRange_ColumnStart();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.first.csvdsl.csvDsl.ColRange#getColumnEnd <em>Column End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Column End</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.ColRange#getColumnEnd()
   * @see #getColRange()
   * @generated
   */
  EAttribute getColRange_ColumnEnd();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Csv_variable <em>Csv variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Csv variable</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Csv_variable
   * @generated
   */
  EClass getCsv_variable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.first.csvdsl.csvDsl.Csv_variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Csv_variable#getName()
   * @see #getCsv_variable()
   * @generated
   */
  EAttribute getCsv_variable_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.first.csvdsl.csvDsl.Int_variable <em>Int variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int variable</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Int_variable
   * @generated
   */
  EClass getInt_variable();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.first.csvdsl.csvDsl.Int_variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.first.csvdsl.csvDsl.Int_variable#getName()
   * @see #getInt_variable()
   * @generated
   */
  EAttribute getInt_variable_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CsvDslFactory getCsvDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.ModelImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Statement</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__STATEMENT = eINSTANCE.getModel_Statement();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.StatementImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.CsvOperationImpl <em>Csv Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvOperationImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getCsvOperation()
     * @generated
     */
    EClass CSV_OPERATION = eINSTANCE.getCsvOperation();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.IntOperationImpl <em>Int Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.IntOperationImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getIntOperation()
     * @generated
     */
    EClass INT_OPERATION = eINSTANCE.getIntOperation();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.AssignImpl <em>Assign</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.AssignImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getAssign()
     * @generated
     */
    EClass ASSIGN = eINSTANCE.getAssign();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGN__VAL = eINSTANCE.getAssign_Val();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGN__OP = eINSTANCE.getAssign_Op();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGN__VAR = eINSTANCE.getAssign_Var();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.SaveImpl <em>Save</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.SaveImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getSave()
     * @generated
     */
    EClass SAVE = eINSTANCE.getSave();

    /**
     * The meta object literal for the '<em><b>Declared csv</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SAVE__DECLARED_CSV = eINSTANCE.getSave_Declared_csv();

    /**
     * The meta object literal for the '<em><b>Filename</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SAVE__FILENAME = eINSTANCE.getSave_Filename();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.PrintImpl <em>Print</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.PrintImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getPrint()
     * @generated
     */
    EClass PRINT = eINSTANCE.getPrint();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRINT__VAL = eINSTANCE.getPrint_Val();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.LoadImpl <em>Load</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.LoadImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getLoad()
     * @generated
     */
    EClass LOAD = eINSTANCE.getLoad();

    /**
     * The meta object literal for the '<em><b>Filename</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOAD__FILENAME = eINSTANCE.getLoad_Filename();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.SumImpl <em>Sum</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.SumImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getSum()
     * @generated
     */
    EClass SUM = eINSTANCE.getSum();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUM__VAR = eINSTANCE.getSum_Var();

    /**
     * The meta object literal for the '<em><b>Selection</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUM__SELECTION = eINSTANCE.getSum_Selection();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.ProductImpl <em>Product</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.ProductImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getProduct()
     * @generated
     */
    EClass PRODUCT = eINSTANCE.getProduct();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCT__VAR = eINSTANCE.getProduct_Var();

    /**
     * The meta object literal for the '<em><b>Selection</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PRODUCT__SELECTION = eINSTANCE.getProduct_Selection();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.DirectImpl <em>Direct</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.DirectImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getDirect()
     * @generated
     */
    EClass DIRECT = eINSTANCE.getDirect();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIRECT__VAL = eINSTANCE.getDirect_Val();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.SelectImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>New Csv</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__NEW_CSV = eINSTANCE.getSelect_NewCsv();

    /**
     * The meta object literal for the '<em><b>Csv var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__CSV_VAR = eINSTANCE.getSelect_Csv_var();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__RANGE = eINSTANCE.getSelect_Range();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.DropImpl <em>Drop</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.DropImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getDrop()
     * @generated
     */
    EClass DROP = eINSTANCE.getDrop();

    /**
     * The meta object literal for the '<em><b>New Csv</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DROP__NEW_CSV = eINSTANCE.getDrop_NewCsv();

    /**
     * The meta object literal for the '<em><b>Csv var</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DROP__CSV_VAR = eINSTANCE.getDrop_Csv_var();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DROP__RANGE = eINSTANCE.getDrop_Range();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.RangeImpl <em>Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.RangeImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getRange()
     * @generated
     */
    EClass RANGE = eINSTANCE.getRange();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.RowRangeImpl <em>Row Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.RowRangeImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getRowRange()
     * @generated
     */
    EClass ROW_RANGE = eINSTANCE.getRowRange();

    /**
     * The meta object literal for the '<em><b>Row</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROW_RANGE__ROW = eINSTANCE.getRowRange_Row();

    /**
     * The meta object literal for the '<em><b>Row Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROW_RANGE__ROW_START = eINSTANCE.getRowRange_RowStart();

    /**
     * The meta object literal for the '<em><b>Row End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROW_RANGE__ROW_END = eINSTANCE.getRowRange_RowEnd();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.ColRangeImpl <em>Col Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.ColRangeImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getColRange()
     * @generated
     */
    EClass COL_RANGE = eINSTANCE.getColRange();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COL_RANGE__COLUMN = eINSTANCE.getColRange_Column();

    /**
     * The meta object literal for the '<em><b>Column Start</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COL_RANGE__COLUMN_START = eINSTANCE.getColRange_ColumnStart();

    /**
     * The meta object literal for the '<em><b>Column End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COL_RANGE__COLUMN_END = eINSTANCE.getColRange_ColumnEnd();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.Csv_variableImpl <em>Csv variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.Csv_variableImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getCsv_variable()
     * @generated
     */
    EClass CSV_VARIABLE = eINSTANCE.getCsv_variable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CSV_VARIABLE__NAME = eINSTANCE.getCsv_variable_Name();

    /**
     * The meta object literal for the '{@link org.xtext.first.csvdsl.csvDsl.impl.Int_variableImpl <em>Int variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.first.csvdsl.csvDsl.impl.Int_variableImpl
     * @see org.xtext.first.csvdsl.csvDsl.impl.CsvDslPackageImpl#getInt_variable()
     * @generated
     */
    EClass INT_VARIABLE = eINSTANCE.getInt_variable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_VARIABLE__NAME = eINSTANCE.getInt_variable_Name();

  }

} //CsvDslPackage
