/**
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.csvDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getRange()
 * @model
 * @generated
 */
public interface Range extends EObject
{
} // Range
