/**
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.csvDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Row Range</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.RowRange#getRow <em>Row</em>}</li>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.RowRange#getRowStart <em>Row Start</em>}</li>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.RowRange#getRowEnd <em>Row End</em>}</li>
 * </ul>
 *
 * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getRowRange()
 * @model
 * @generated
 */
public interface RowRange extends Range
{
  /**
   * Returns the value of the '<em><b>Row</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row</em>' attribute.
   * @see #setRow(int)
   * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getRowRange_Row()
   * @model
   * @generated
   */
  int getRow();

  /**
   * Sets the value of the '{@link org.xtext.first.csvdsl.csvDsl.RowRange#getRow <em>Row</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row</em>' attribute.
   * @see #getRow()
   * @generated
   */
  void setRow(int value);

  /**
   * Returns the value of the '<em><b>Row Start</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row Start</em>' attribute.
   * @see #setRowStart(int)
   * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getRowRange_RowStart()
   * @model
   * @generated
   */
  int getRowStart();

  /**
   * Sets the value of the '{@link org.xtext.first.csvdsl.csvDsl.RowRange#getRowStart <em>Row Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row Start</em>' attribute.
   * @see #getRowStart()
   * @generated
   */
  void setRowStart(int value);

  /**
   * Returns the value of the '<em><b>Row End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Row End</em>' attribute.
   * @see #setRowEnd(int)
   * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getRowRange_RowEnd()
   * @model
   * @generated
   */
  int getRowEnd();

  /**
   * Sets the value of the '{@link org.xtext.first.csvdsl.csvDsl.RowRange#getRowEnd <em>Row End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Row End</em>' attribute.
   * @see #getRowEnd()
   * @generated
   */
  void setRowEnd(int value);

} // RowRange
