/**
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.csvDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Save</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.Save#getDeclared_csv <em>Declared csv</em>}</li>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.Save#getFilename <em>Filename</em>}</li>
 * </ul>
 *
 * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getSave()
 * @model
 * @generated
 */
public interface Save extends Statement
{
  /**
   * Returns the value of the '<em><b>Declared csv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Declared csv</em>' containment reference.
   * @see #setDeclared_csv(Csv_variable)
   * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getSave_Declared_csv()
   * @model containment="true"
   * @generated
   */
  Csv_variable getDeclared_csv();

  /**
   * Sets the value of the '{@link org.xtext.first.csvdsl.csvDsl.Save#getDeclared_csv <em>Declared csv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Declared csv</em>' containment reference.
   * @see #getDeclared_csv()
   * @generated
   */
  void setDeclared_csv(Csv_variable value);

  /**
   * Returns the value of the '<em><b>Filename</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Filename</em>' attribute.
   * @see #setFilename(String)
   * @see org.xtext.first.csvdsl.csvDsl.CsvDslPackage#getSave_Filename()
   * @model
   * @generated
   */
  String getFilename();

  /**
   * Sets the value of the '{@link org.xtext.first.csvdsl.csvDsl.Save#getFilename <em>Filename</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Filename</em>' attribute.
   * @see #getFilename()
   * @generated
   */
  void setFilename(String value);

} // Save
