/**
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.csvDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.first.csvdsl.csvDsl.ColRange;
import org.xtext.first.csvdsl.csvDsl.CsvDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Col Range</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.impl.ColRangeImpl#getColumn <em>Column</em>}</li>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.impl.ColRangeImpl#getColumnStart <em>Column Start</em>}</li>
 *   <li>{@link org.xtext.first.csvdsl.csvDsl.impl.ColRangeImpl#getColumnEnd <em>Column End</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ColRangeImpl extends RangeImpl implements ColRange
{
  /**
   * The default value of the '{@link #getColumn() <em>Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumn()
   * @generated
   * @ordered
   */
  protected static final int COLUMN_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getColumn() <em>Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumn()
   * @generated
   * @ordered
   */
  protected int column = COLUMN_EDEFAULT;

  /**
   * The default value of the '{@link #getColumnStart() <em>Column Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumnStart()
   * @generated
   * @ordered
   */
  protected static final int COLUMN_START_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getColumnStart() <em>Column Start</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumnStart()
   * @generated
   * @ordered
   */
  protected int columnStart = COLUMN_START_EDEFAULT;

  /**
   * The default value of the '{@link #getColumnEnd() <em>Column End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumnEnd()
   * @generated
   * @ordered
   */
  protected static final int COLUMN_END_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getColumnEnd() <em>Column End</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumnEnd()
   * @generated
   * @ordered
   */
  protected int columnEnd = COLUMN_END_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ColRangeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CsvDslPackage.Literals.COL_RANGE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getColumn()
  {
    return column;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColumn(int newColumn)
  {
    int oldColumn = column;
    column = newColumn;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CsvDslPackage.COL_RANGE__COLUMN, oldColumn, column));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getColumnStart()
  {
    return columnStart;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColumnStart(int newColumnStart)
  {
    int oldColumnStart = columnStart;
    columnStart = newColumnStart;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CsvDslPackage.COL_RANGE__COLUMN_START, oldColumnStart, columnStart));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getColumnEnd()
  {
    return columnEnd;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColumnEnd(int newColumnEnd)
  {
    int oldColumnEnd = columnEnd;
    columnEnd = newColumnEnd;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CsvDslPackage.COL_RANGE__COLUMN_END, oldColumnEnd, columnEnd));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CsvDslPackage.COL_RANGE__COLUMN:
        return getColumn();
      case CsvDslPackage.COL_RANGE__COLUMN_START:
        return getColumnStart();
      case CsvDslPackage.COL_RANGE__COLUMN_END:
        return getColumnEnd();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CsvDslPackage.COL_RANGE__COLUMN:
        setColumn((Integer)newValue);
        return;
      case CsvDslPackage.COL_RANGE__COLUMN_START:
        setColumnStart((Integer)newValue);
        return;
      case CsvDslPackage.COL_RANGE__COLUMN_END:
        setColumnEnd((Integer)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CsvDslPackage.COL_RANGE__COLUMN:
        setColumn(COLUMN_EDEFAULT);
        return;
      case CsvDslPackage.COL_RANGE__COLUMN_START:
        setColumnStart(COLUMN_START_EDEFAULT);
        return;
      case CsvDslPackage.COL_RANGE__COLUMN_END:
        setColumnEnd(COLUMN_END_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CsvDslPackage.COL_RANGE__COLUMN:
        return column != COLUMN_EDEFAULT;
      case CsvDslPackage.COL_RANGE__COLUMN_START:
        return columnStart != COLUMN_START_EDEFAULT;
      case CsvDslPackage.COL_RANGE__COLUMN_END:
        return columnEnd != COLUMN_END_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (column: ");
    result.append(column);
    result.append(", columnStart: ");
    result.append(columnStart);
    result.append(", columnEnd: ");
    result.append(columnEnd);
    result.append(')');
    return result.toString();
  }

} //ColRangeImpl
