/**
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.csvDsl.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.first.csvdsl.csvDsl.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CsvDslFactoryImpl extends EFactoryImpl implements CsvDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CsvDslFactory init()
  {
    try
    {
      CsvDslFactory theCsvDslFactory = (CsvDslFactory)EPackage.Registry.INSTANCE.getEFactory(CsvDslPackage.eNS_URI);
      if (theCsvDslFactory != null)
      {
        return theCsvDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CsvDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CsvDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CsvDslPackage.MODEL: return createModel();
      case CsvDslPackage.STATEMENT: return createStatement();
      case CsvDslPackage.CSV_OPERATION: return createCsvOperation();
      case CsvDslPackage.INT_OPERATION: return createIntOperation();
      case CsvDslPackage.ASSIGN: return createAssign();
      case CsvDslPackage.SAVE: return createSave();
      case CsvDslPackage.PRINT: return createPrint();
      case CsvDslPackage.LOAD: return createLoad();
      case CsvDslPackage.SUM: return createSum();
      case CsvDslPackage.PRODUCT: return createProduct();
      case CsvDslPackage.DIRECT: return createDirect();
      case CsvDslPackage.SELECT: return createSelect();
      case CsvDslPackage.DROP: return createDrop();
      case CsvDslPackage.RANGE: return createRange();
      case CsvDslPackage.ROW_RANGE: return createRowRange();
      case CsvDslPackage.COL_RANGE: return createColRange();
      case CsvDslPackage.CSV_VARIABLE: return createCsv_variable();
      case CsvDslPackage.INT_VARIABLE: return createInt_variable();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Statement createStatement()
  {
    StatementImpl statement = new StatementImpl();
    return statement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CsvOperation createCsvOperation()
  {
    CsvOperationImpl csvOperation = new CsvOperationImpl();
    return csvOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntOperation createIntOperation()
  {
    IntOperationImpl intOperation = new IntOperationImpl();
    return intOperation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Assign createAssign()
  {
    AssignImpl assign = new AssignImpl();
    return assign;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Save createSave()
  {
    SaveImpl save = new SaveImpl();
    return save;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Print createPrint()
  {
    PrintImpl print = new PrintImpl();
    return print;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Load createLoad()
  {
    LoadImpl load = new LoadImpl();
    return load;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Sum createSum()
  {
    SumImpl sum = new SumImpl();
    return sum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Product createProduct()
  {
    ProductImpl product = new ProductImpl();
    return product;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Direct createDirect()
  {
    DirectImpl direct = new DirectImpl();
    return direct;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Select createSelect()
  {
    SelectImpl select = new SelectImpl();
    return select;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Drop createDrop()
  {
    DropImpl drop = new DropImpl();
    return drop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Range createRange()
  {
    RangeImpl range = new RangeImpl();
    return range;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RowRange createRowRange()
  {
    RowRangeImpl rowRange = new RowRangeImpl();
    return rowRange;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ColRange createColRange()
  {
    ColRangeImpl colRange = new ColRangeImpl();
    return colRange;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Csv_variable createCsv_variable()
  {
    Csv_variableImpl csv_variable = new Csv_variableImpl();
    return csv_variable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Int_variable createInt_variable()
  {
    Int_variableImpl int_variable = new Int_variableImpl();
    return int_variable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CsvDslPackage getCsvDslPackage()
  {
    return (CsvDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CsvDslPackage getPackage()
  {
    return CsvDslPackage.eINSTANCE;
  }

} //CsvDslFactoryImpl
