/**
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.csvDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.first.csvdsl.csvDsl.CsvDslPackage;
import org.xtext.first.csvdsl.csvDsl.CsvOperation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Csv Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class CsvOperationImpl extends MinimalEObjectImpl.Container implements CsvOperation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CsvOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CsvDslPackage.Literals.CSV_OPERATION;
  }

} //CsvOperationImpl
