/*
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class CsvDslUiModule extends AbstractCsvDslUiModule {

	public CsvDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
