/*
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.CsvDsl.ui.internal.CsvDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CsvDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CsvDslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CsvDslActivator activator = CsvDslActivator.getInstance();
		return activator != null ? activator.getInjector(CsvDslActivator.ORG_XTEXT_FIRST_CSVDSL_CSVDSL) : null;
	}

}
