/*
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.first.csvdsl.parser.antlr.internal.InternalCsvDslParser;
import org.xtext.first.csvdsl.services.CsvDslGrammarAccess;

public class CsvDslParser extends AbstractAntlrParser {

	@Inject
	private CsvDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCsvDslParser createParser(XtextTokenStream stream) {
		return new InternalCsvDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public CsvDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CsvDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
