/*
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class CsvDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/first/csvdsl/parser/antlr/internal/InternalCsvDsl.tokens");
	}
}
