/*
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractCsvDslScopeProvider extends DelegatingScopeProvider {
}
