/*
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class CsvDslStandaloneSetup extends CsvDslStandaloneSetupGenerated {

	public static void doSetup() {
		new CsvDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
