/*
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CsvDslRuntimeModule extends AbstractCsvDslRuntimeModule {
}
