/*
 * generated by Xtext 2.28.0
 */
package org.xtext.first.csvdsl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class CsvDslScopeProvider extends AbstractCsvDslScopeProvider {

}
